#! /bin/sh

#-----------------------------------------------------------------------
# $1=OS, $2=Platform
Release_GUI()
{
#-----------------------------------------------------------------------
# Clean up
test -e BWF_MetaEdit_GUI_$1_$2.tar     && rm    BWF_MetaEdit_GUI_$1_$2.tar
test -e BWF_MetaEdit_GUI_$1_$2.tar.bz2 && rm    BWF_MetaEdit_GUI_$1_$2.tar.bz2
test -d BWF_MetaEdit_GUI_$1_$2         && rm -r BWF_MetaEdit_GUI_$1_$2
mkdir   BWF_MetaEdit_GUI_$1_$2

#-----------------------------------------------------------------------
# Copying : Exe
cp ../Project/GNU/GUI/bwfmetaedit-gui BWF_MetaEdit_GUI_$1_$2/bwfmetaedit-gui
cd BWF_MetaEdit_GUI_$1_$2
strip bwfmetaedit-gui
cd ..

#-----------------------------------------------------------------------
# Copying : Information file
cp ../License.html BWF_MetaEdit_GUI_$1_$2/
cp ../History_GUI.txt BWF_MetaEdit_GUI_$1_$2/History.txt
cp ../conformance_point_document.xsd BWF_MetaEdit_GUI_$1_$2
cp ReadMe_GUI_$1.txt BWF_MetaEdit_GUI_$1_$2/ReadMe.txt

#-----------------------------------------------------------------------
# Compressing Archive
tar jchf BWF_MetaEdit_GUI_$1_$2.tar.bz2 BWF_MetaEdit_GUI_$1_$2

#-----------------------------------------------------------------------
# Clean up
#if "%1"=="SkipCleanUp" goto SkipCleanUp
#rm -r BWF_MetaEdit_GUI_$1_$2
#:SkipCleanUp
}

