#! /bin/sh

#-----------------------------------------------------------------------
# $1=bwfmetaedit Package version,
# $2=,
# $3=,
# $4=,
# $5=,
# $6=,
# $7=Platform, $8=CPU, $9=CPU target
Download_Packages()
{
#-----------------------------------------------------------------------
# Downloading
wget "http://download.opensuse.org/repositories/home:/MediaArea_net/$7/$8/bwfmetaedit$dash$bwfmetaeditv-$1$9.$type"
mv bwfmetaedit$dash$bwfmetaeditv-$1$9.$type \
 download/binary/bwfmetaedit/$bwfmetaeditv/bwfmetaedit$dash$bwfmetaeditv-$destversion$9.$7.$type

wget "http://download.opensuse.org/repositories/home:/MediaArea_net/$7/$8/bwfmetaedit-gui$dash$bwfmetaeditv-$1$9.$type"
mv bwfmetaedit-gui$dash$bwfmetaeditv-$1$9.$type \
 download/binary/bwfmetaedit-gui/$bwfmetaeditv/bwfmetaedit-gui$dash$bwfmetaeditv-$destversion$9.$7.$type
}

#-----------------------------------------------------------------------
# $1=bwfmetaedit version
Download_Global()
{
#-----------------------------------------------------------------------
# Clean up
rm download/binary/bwfmetaedit/$bwfmetaeditv/*.rpm -f
rm download/binary/bwfmetaedit/$bwfmetaeditv/*.deb -f
rm download/binary/bwfmetaedit-gui/$bwfmetaeditv/*.rpm -f
rm download/binary/bwfmetaedit-gui/$bwfmetaeditv/*.deb -f
mkdir download/binary/bwfmetaedit/$bwfmetaeditv
mkdir download/binary/bwfmetaedit-gui/$bwfmetaeditv

#-----------------------------------------------------------------------
# Downloading
type="deb"
devext="dev"
dash="_"
Download_Packages 1  x  x  x x x   Debian_5      i386   _i386
Download_Packages 1  x  x  x x x   Debian_5      amd64 _amd64
Download_Packages 1  x  x  x x x   Debian_6.0    i386   _i386
Download_Packages 1  x  x  x x x   Debian_6.0    amd64  _amd64
Download_Packages 1  x  x  x x x   Ubuntu_9.04   i386   _i386
Download_Packages 1  x  x  x x x   Ubuntu_9.04   amd64  _amd64
Download_Packages 1  x  x  x x x   Ubuntu_9.10   i386   _i386
Download_Packages 1  x  x  x x x   Ubuntu_9.10   amd64  _amd64
Download_Packages 1  x  x  x x x   Ubuntu_10.04  i386   _i386
Download_Packages 1  x  x  x x x   Ubuntu_10.04  amd64  _amd64
Download_Packages 1  x  x  x x x   Ubuntu_10.10  i386   _i386
Download_Packages 1  x  x  x x x   Ubuntu_10.10  amd64  _amd64
Download_Packages 1  x  x  x x x   Ubuntu_11.04  i386   _i386
Download_Packages 1  x  x  x x x   Ubuntu_11.04  amd64  _amd64
Download_Packages 1  x  x  x x x   Ubuntu_11.10  i386   _i386
Download_Packages 1  x  x  x x x   Ubuntu_11.10  amd64  _amd64

type="rpm"
devext="devel"
dash="-"
Download_Packages $1  x  x x x x   CentOS_5        i386   .i386
Download_Packages $1  x  x x x x   CentOS_5        x86_64 .x86_64
Download_Packages $1  x  x x x x   CentOS_6        i386   .i386
Download_Packages $1  x  x x x x   CentOS_6        x86_64 .x86_64
Download_Packages $1  x  x x x x   Fedora_15       i386   .i386
Download_Packages $1  x  x x x x   Fedora_15       x86_64 .x86_64
Download_Packages $1  x  x x x x   Fedora_16       i386   .i386
Download_Packages $1  x  x x x x   Fedora_16       x86_64 .x86_64
Download_Packages $1  x  x x x x   Mandriva_2009.1 i586   .i586
Download_Packages $1  x  x x x x   Mandriva_2009.1 x86_64 .x86_64
Download_Packages $1  x  x x x x   Mandriva_2010   i586   .i586
Download_Packages $1  x  x x x x   Mandriva_2010   x86_64 .x86_64
Download_Packages $1  x  x x x x   Mandriva_2010.1 i586   .i586
Download_Packages $1  x  x x x x   Mandriva_2010.1 x86_64 .x86_64
Download_Packages $1  x  x x x x   Mandriva_2011   i586   .i586
Download_Packages $1  x  x x x x   Mandriva_2011   x86_64 .x86_64
Download_Packages $1  x  x x x x   RHEL_5          i386   .i386
Download_Packages $1  x  x x x x   RHEL_5          x86_64 .x86_64
Download_Packages $1  x  x x x x   RHEL_6          i386   .i386
Download_Packages $1  x  x x x x   RHEL_6          x86_64 .x86_64
Download_Packages $1  x  x x x x   SLE_11          i586   .i586
Download_Packages $1  x  x x x x   SLE_11          x86_64 .x86_64
Download_Packages $1  x  x x x x   SLE_11_SP1      i586   .i586
Download_Packages $1  x  x x x x   SLE_11_SP1      x86_64 .x86_64
Download_Packages $1  x  x x x x   openSUSE_11.4   i586   .i586
Download_Packages $1  x  x x x x   openSUSE_11.4   x86_64 .x86_64
Download_Packages $1  x  x x x x   openSUSE_12.1   i586   .i586
Download_Packages $1  x  x x x x   openSUSE_12.1   x86_64 .x86_64
}


bwfmetaeditv="1.2.0"
destversion="1"

Download_Global 30.1
