name: Checks

on: [push, pull_request]

jobs:
  Unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update -y
            sudo apt-get install -y libxml2-utils libxml2-dev zlib1g-dev qtquickcontrols2-5-dev qt6-base-dev qt6-declarative-dev qt6-svg-dev qmake6 ffmpeg
          fi
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install automake qt ffmpeg
          fi
      - name: Configure
        run: |
          cd Project/GNU/CLI
          autoreconf -if
          ./configure
      - name: Build
        run: |
          cd Project/GNU/CLI
          make
      - name: Check
        run: |
          cd Project/GNU/CLI
          make check
      - name: Configure GUI
        run: |
          cd Project/QtCreator
          if [ "$RUNNER_OS" == "macOS" ]; then
            sed -i '' 's|QMAKE_APPLE_DEVICE_ARCHS|# QMAKE_APPLE_DEVICE_ARCHS|g' bwfmetaedit-gui.pro
          fi
          qmake6
      - name: Build GUI
        run: |
          cd Project/QtCreator
          make
